2023-03-28 21:09:30,960:[critical]	./LimbusLocalize/assets/Localize/CN/CN_P10504.json
	Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 153, in main
    last = check(merge(transform(fetch_json(i))), last)
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 88, in transform
    if len(data[keys[0]]["dataList"]) == len(data[keys[1]]["dataList"]) == len(data[keys[-1]]["dataList"]) == len(data[keys[-2]]["dataList"]):
IndexError: list index out of range

2023-03-28 21:09:30,996:[critical]	./LimbusLocalize/assets/Localize/CN/CN_AbEvents_Mirror.json
	Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 153, in main
    last = check(merge(transform(fetch_json(i))), last)
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 100, in transform
    for q in h.keys():
AttributeError: 'str' object has no attribute 'keys'

2023-03-28 21:09:31,003:[ERROR]	./LimbusLocalize/assets/Localize/CN/CN_S204B.json load error
2023-03-28 21:09:31,040:[critical]	./LimbusLocalize/assets/Localize/CN/CN_S204B.json
	Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 77, in fetch_json
    fin[i] = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 61 column 47 (char 1194)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 153, in main
    last = check(merge(transform(fetch_json(i))), last)
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 81, in fetch_json
    fin[i] = eval(f.read())
  File "<string>", line 61
    "content": "你们两个，直到现在都觉得我们是毫无价值的人渣吧，不是吗？
               ^
SyntaxError: unterminated string literal (detected at line 61)

2023-03-28 21:09:31,099:[critical]	./LimbusLocalize/assets/Localize/CN/CN_AttendanceRewardsText.json
	Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 153, in main
    last = check(merge(transform(fetch_json(i))), last)
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 88, in transform
    if len(data[keys[0]]["dataList"]) == len(data[keys[1]]["dataList"]) == len(data[keys[-1]]["dataList"]) == len(data[keys[-2]]["dataList"]):
IndexError: list index out of range

2023-03-28 21:09:31,132:[critical]	./LimbusLocalize/assets/Localize/CN/CN_Voice_Heathcliff_Ncorp_10704.json
	Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 153, in main
    last = check(merge(transform(fetch_json(i))), last)
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 88, in transform
    if len(data[keys[0]]["dataList"]) == len(data[keys[1]]["dataList"]) == len(data[keys[-1]]["dataList"]) == len(data[keys[-2]]["dataList"]):
IndexError: list index out of range

2023-03-28 21:09:31,151:[critical]	./LimbusLocalize/assets/Localize/CN/CN_Voice_Meursault_Ncorp_10504.json
	Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 153, in main
    last = check(merge(transform(fetch_json(i))), last)
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 88, in transform
    if len(data[keys[0]]["dataList"]) == len(data[keys[1]]["dataList"]) == len(data[keys[-1]]["dataList"]) == len(data[keys[-2]]["dataList"]):
IndexError: list index out of range

2023-03-28 21:09:31,203:[critical]	./LimbusLocalize/assets/Localize/CN/CN_P10904.json
	Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 153, in main
    last = check(merge(transform(fetch_json(i))), last)
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 88, in transform
    if len(data[keys[0]]["dataList"]) == len(data[keys[1]]["dataList"]) == len(data[keys[-1]]["dataList"]) == len(data[keys[-2]]["dataList"]):
IndexError: list index out of range

2023-03-28 21:09:31,204:[critical]	./LimbusLocalize/assets/Localize/CN/CN_P10204.json
	Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 153, in main
    last = check(merge(transform(fetch_json(i))), last)
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 88, in transform
    if len(data[keys[0]]["dataList"]) == len(data[keys[1]]["dataList"]) == len(data[keys[-1]]["dataList"]) == len(data[keys[-2]]["dataList"]):
IndexError: list index out of range

2023-03-28 21:09:31,205:[critical]	./LimbusLocalize/assets/Localize/CN/CN_SeasonTitle.json
	Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 153, in main
    last = check(merge(transform(fetch_json(i))), last)
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 88, in transform
    if len(data[keys[0]]["dataList"]) == len(data[keys[1]]["dataList"]) == len(data[keys[-1]]["dataList"]) == len(data[keys[-2]]["dataList"]):
IndexError: list index out of range

2023-03-28 21:09:31,372:[ERROR]	./LimbusLocalize/assets/Localize/CN/CN_S102B.json load error
2023-03-28 21:09:31,372:[critical]	./LimbusLocalize/assets/Localize/CN/CN_S102B.json
	Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 77, in fetch_json
    fin[i] = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 7 column 30 (char 121)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 153, in main
    last = check(merge(transform(fetch_json(i))), last)
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 81, in fetch_json
    fin[i] = eval(f.read())
  File "<string>", line 7
    "content": "不好意思！我有个问题！
               ^
SyntaxError: unterminated string literal (detected at line 7)

2023-03-28 21:09:31,375:[ERROR]	./LimbusLocalize/assets/Localize/CN/CN_S101B.json load error
2023-03-28 21:09:31,376:[critical]	./LimbusLocalize/assets/Localize/CN/CN_S101B.json
	Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 77, in fetch_json
    fin[i] = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 9 column 27 (char 126)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 153, in main
    last = check(merge(transform(fetch_json(i))), last)
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 81, in fetch_json
    fin[i] = eval(f.read())
  File "<string>", line 9
    "place": "梅菲斯托费勒斯 内部
             ^
SyntaxError: unterminated string literal (detected at line 9)

2023-03-28 21:09:31,438:[critical]	./LimbusLocalize/assets/Localize/CN/CN_NickName.json
	Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 153, in main
    last = check(merge(transform(fetch_json(i))), last)
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 88, in transform
    if len(data[keys[0]]["dataList"]) == len(data[keys[1]]["dataList"]) == len(data[keys[-1]]["dataList"]) == len(data[keys[-2]]["dataList"]):
KeyError: 'dataList'

2023-03-28 21:09:31,565:[critical]	./LimbusLocalize/assets/Localize/CN/CN_RewardDungeonUI.json
	Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 153, in main
    last = check(merge(transform(fetch_json(i))), last)
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 88, in transform
    if len(data[keys[0]]["dataList"]) == len(data[keys[1]]["dataList"]) == len(data[keys[-1]]["dataList"]) == len(data[keys[-2]]["dataList"]):
IndexError: list index out of range

2023-03-28 21:09:31,764:[critical]	./LimbusLocalize/assets/Localize/CN/CN_Voice_Rodion_Ncorp_10904.json
	Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 153, in main
    last = check(merge(transform(fetch_json(i))), last)
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 88, in transform
    if len(data[keys[0]]["dataList"]) == len(data[keys[1]]["dataList"]) == len(data[keys[-1]]["dataList"]) == len(data[keys[-2]]["dataList"]):
IndexError: list index out of range

2023-03-28 21:09:31,801:[ERROR]	./LimbusLocalize/assets/Localize/CN/CN_S209B.json load error
2023-03-28 21:09:31,802:[critical]	./LimbusLocalize/assets/Localize/CN/CN_S209B.json
	Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 77, in fetch_json
    fin[i] = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 21 column 40 (char 367)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 153, in main
    last = check(merge(transform(fetch_json(i))), last)
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 81, in fetch_json
    fin[i] = eval(f.read())
  File "<string>", line 21
    "content": "听到以实玛利的话，良秀摇了摇头，摆出一副"看好了"的表情。"
               ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?

2023-03-28 21:09:31,993:[critical]	./LimbusLocalize/assets/Localize/CN/CN_AbEvents.json
	Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 153, in main
    last = check(merge(transform(fetch_json(i))), last)
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 100, in transform
    for q in h.keys():
AttributeError: 'str' object has no attribute 'keys'

2023-03-28 21:09:32,049:[critical]	./LimbusLocalize/assets/Localize/CN/CN_Voice_Faust_Ncorp_10204.json
	Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 153, in main
    last = check(merge(transform(fetch_json(i))), last)
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 88, in transform
    if len(data[keys[0]]["dataList"]) == len(data[keys[1]]["dataList"]) == len(data[keys[-1]]["dataList"]) == len(data[keys[-2]]["dataList"]):
IndexError: list index out of range

2023-03-28 21:09:32,074:[critical]	./LimbusLocalize/assets/Localize/CN/CN_P10704.json
	Traceback (most recent call last):
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 153, in main
    last = check(merge(transform(fetch_json(i))), last)
  File "/home/runner/work/Limbus-Company-Work-Dataset/Limbus-Company-Work-Dataset/run.py", line 88, in transform
    if len(data[keys[0]]["dataList"]) == len(data[keys[1]]["dataList"]) == len(data[keys[-1]]["dataList"]) == len(data[keys[-2]]["dataList"]):
IndexError: list index out of range

